FROM node:22-alpine

# Definir diretório de trabalho
WORKDIR /app

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm ci

# Copiar o restante do código
COPY . .

# importante para gerar relatórios de cobertura dentro de /app/coverage
VOLUME ["/app/coverage"]

# executa a suite de testes em modo CI
CMD ["npm", "run", "test:ci"]
