name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-server:
    name: Lint & Prettier (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci --prefix server

      - name: Rodar ESLint
        run: npm run lint --prefix server

      - name: Verificar formatação (Prettier)
        run: npm run format:check --prefix server

  lint-front:
    name: Lint & Prettier (Front)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci --prefix front

      - name: Rodar ESLint
        run: npm run lint --prefix front

      - name: Verificar formatação (Prettier)
        run: npm run format:check --prefix front

  build-server:
    name: Build TypeScript (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci --prefix server

      - name: Compilar código
        run: npm run build --prefix server

  unit-tests:
    name: Testes Unitários (Server)
    runs-on: ubuntu-latest
    needs: [lint-server, build-server]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes unitários
        run: |
          docker compose -f docker-compose.unit.yml up --build --abort-on-container-exit --exit-code-from  node-unit-test

      - name: Upload coverage report (unit)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.unit.yml down -v || true

  integration-tests:
    name: Testes de Integração (Server)
    runs-on: ubuntu-latest
    needs: [lint-server, build-server]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes de integração
        run: |
          docker compose -f docker-compose.integration.yml up --build --abort-on-container-exit --exit-code-from node-integration-test

      - name: Upload coverage report (integration)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.integration.yml down -v || true

  server-e2e-tests:
    name: Testes End-to-End (Server)
    runs-on: ubuntu-latest
    needs: [lint-server, build-server]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes E2E
        run: |
          docker compose --env-file .env.e2e.server -f docker-compose.e2e-server.yml up --build --abort-on-container-exit --exit-code-from node-e2e-test
      
      - name: Listar conteúdo de coverage
        if: success() || failure()
        run: ls -R server/coverage || true
      
      - name: Upload coverage report (e2e)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-e2e
          path: server/coverage

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.e2e-server.yml down -v || true

  front-e2e-tests:
    name: Testes End-to-End (Front)
    runs-on: ubuntu-latest
    needs: [lint-front]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rodar testes E2E Front
        run: |
          docker compose --env-file .env.e2e.front -f docker-compose.e2e-front.yml \
            up --build --abort-on-container-exit --exit-code-from front-e2e-test

      - name: Upload Playwright HTML Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: front/playwright-report

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.e2e-front.yml down -v || true
